import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:get/get.dart';

class PdfService extends GetxService {
  static PdfService get to => Get.find();

  Future<void> generateBookingPdf(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("Event Booking Summary - Trayza", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 24)),
              ),
              pw.SizedBox(height: 20),
              pw.Text("Client: ${data['name']}"),
              pw.Text("Mobile: ${data['mobile_no']}"),
              pw.Text("Event Date: ${data['date']}"),
              pw.Divider(),
              pw.Text("Total Amount: ₹${data['grandTotalAmount']}"),
              pw.SizedBox(height: 40),
              pw.Footer(
                trailing: pw.Text("Generated by Trayza Admin App"),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
